'use client'

import { useState } from 'react'
import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, ChevronRight, CircleDot, FileSearch, Gauge, Menu, Play, Search, ShieldCheck, SlidersHorizontal, Sparkles, X } from 'lucide-react'

const findings = [{ title: 'Missing authorization check', path: 'src/api/projects/[id]/route.ts', severity: 'High', color: 'coral' }, { title: 'Unvalidated redirect target', path: 'src/auth/callback.ts', severity: 'Medium', color: 'amber' }, { title: 'Dependency update available', path: 'package.json', severity: 'Low', color: 'blue' }]
const nav = [{ label: 'Overview', icon: Gauge }, { label: 'Findings', icon: AlertTriangle }, { label: 'Scan history', icon: Activity }]

export default function Home() {
  const [active, setActive] = useState('Overview'); const [running, setRunning] = useState(false); const [menu, setMenu] = useState(false)
  function runScan() { setRunning(true); window.setTimeout(() => setRunning(false), 1800) }
  return <main className="app-shell">
    <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMenu(!menu)} aria-label="Open navigation"><Menu size={20}/></button><div className="brand"><span className="brand-mark"><ShieldCheck size={18}/></span><span>OmniForge</span><small>SECURITY</small></div><div className="header-actions"><span className="status"><CircleDot size={12}/> Harness ready</span><button className="avatar" aria-label="Account">C</button></div></header>
    <div className="workspace"><aside className={menu ? 'sidebar open' : 'sidebar'}><div className="project"><span className="project-icon">CS</span><div><strong>codex-security</strong><span>Local workspace</span></div><ChevronRight size={16}/></div><nav>{nav.map(({label, icon: Icon}) => <button key={label} className={active === label ? 'nav-item active' : 'nav-item'} onClick={() => {setActive(label);setMenu(false)}}><Icon size={18}/>{label}{label === 'Findings' && <b>3</b>}</button>)}</nav><div className="side-bottom"><button className="nav-item"><SlidersHorizontal size={18}/> Harness settings</button><div className="mode-card"><Sparkles size={16}/><div><strong>Expert mode</strong><span>Deep analysis enabled</span></div><span className="switch on"/></div></div></aside>
    <section className="content"><div className="page-heading"><div><p className="eyebrow">APPLICATION SECURITY / {active.toUpperCase()}</p><h1>{active === 'Overview' ? 'Good morning, Chris.' : active}</h1><p className="subhead">Your security posture at a glance.</p></div><button className="primary" onClick={runScan} disabled={running}>{running ? <><Activity size={17} className="spin"/> Scanning…</> : <><Play size={17} fill="currentColor"/> Run scan</>}</button></div>
      <div className="scan-banner"><div className="banner-icon"><ShieldCheck size={21}/></div><div><strong>Workspace protected</strong><span>Last scan completed today at 09:42 · 2m 18s</span></div><button className="text-button">View report <ArrowUpRight size={15}/></button></div>
      <div className="metrics"><Metric label="Security score" value="87" suffix="/100" trend="+6 this week" good/><Metric label="Open findings" value="3" trend="1 high priority"/><Metric label="Files analyzed" value="1,248" trend="Across 6 packages"/></div>
      <div className="grid"><section className="panel findings"><div className="panel-head"><div><h2>Needs attention</h2><p>Prioritized by exploitability and impact</p></div><button className="ghost">See all <ChevronRight size={15}/></button></div>{findings.map((f) => <div className="finding" key={f.title}><span className={`severity ${f.color}`}><AlertTriangle size={15}/></span><div className="finding-copy"><strong>{f.title}</strong><span>{f.path}</span></div><span className={`tag ${f.color}`}>{f.severity}</span><ChevronRight size={17} className="muted"/></div>)}</section><section className="panel activity"><div className="panel-head"><div><h2>Scan activity</h2><p>Recent harness operations</p></div><button className="icon-button" aria-label="Search activity"><Search size={17}/></button></div><div className="timeline"><Event title="Full repository scan" meta="Today, 09:42 · 1,248 files" icon={<CheckCircle2/>} done/><Event title="Threat model refreshed" meta="Yesterday, 16:18 · 6 attack paths" icon={<ShieldCheck/>} done/><Event title="Baseline configured" meta="Sep 14, 11:06 · Codex Security" icon={<FileSearch/>} done/></div></section></div>
      <footer><span><span className="pulse"/> Codex Security engine v2.4.1</span><span>All analysis stays in your workspace</span></footer></section></div>{running && <div className="toast"><Activity size={17} className="spin"/> Deep scan in progress <button onClick={() => setRunning(false)} aria-label="Dismiss"><X size={15}/></button></div>}
  </main>
}
function Metric({label,value,suffix,trend,good}:{label:string,value:string,suffix?:string,trend:string,good?:boolean}) { return <div className="metric"><span>{label}</span><strong>{value}<small>{suffix}</small></strong><em className={good ? 'good' : ''}>{good && '↗ '}{trend}</em></div> }
function Event({title,meta,icon,done}:{title:string,meta:string,icon:React.ReactNode,done?:boolean}) { return <div className="event"><span className={done ? 'event-icon done' : 'event-icon'}>{icon}</span><div><strong>{title}</strong><span>{meta}</span></div></div> }
